exit step

diff --git a/.github/workflows/figma-pipeline.yml b/.github/workflows/figma-pipeline.yml
--- a/.github/workflows/figma-pipeline.yml
+++ b/.github/workflows/figma-pipeline.yml
@@ -35,7 +35,9 @@ jobs:
           new_branch: update-figma-variables
       - name: Failed to commit
         if: ${{ failure() && steps.commit.conclusion == 'failure' }}
-        run: echo "Failed to commit changes"
+        run: |
+          exit 1
+          echo "Failed to commit changes"
       - name: Create Pull Request
         run: gh pr create -B main -H update-figma-variables --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
         env:
